CREATE TABLE products (
  id SERIAL PRIMARY KEY,
  barcode VARCHAR(100) UNIQUE,
  name VARCHAR(255) NOT NULL,
  price NUMERIC(10,2) NOT NULL,
  cost NUMERIC(10,2),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
