name: Test Runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Show Machine
        run: hostname

      - name: Show Current Directory
        run: pwd

      - name: Show Docker Version
        run: docker --version